production:
  adapter: mysql
  encoding: utf8
  database: ginst
  pool: 5
  username: root
  password: 
  host: localhost
development:
  adapter: mysql
  encoding: utf8
  database: ginst
  pool: 5
  username: root
  password: 
  host: localhost
